### ISSUE TITLE
Could be possible add info about the jail

### ISSUE THREAD

**Issue by castillo92** [deividgdt/fail2ban_telegram_notifications#2]
Hello! Your script works great for me at the first try. I found a very good tutorial from you in NextCloud Support Forum.

Now, I would like to pass to Telegram the name of the Jail that block the IP. 

Looking at `/etc/fail2ban/jail.conf`  I saw:
```
# The simplest action to take: ban only
action_ = %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%($
```
And:
```
# "filter" defines the filter to use by the jail.
#  By default jails have names matching their filter name
#
filter = %(__name__)s[mode=%(mode)s]
```

So... is `name=%(__name__)s,` the way of obtain the jail name? If yes, could you help me edit your script to make possible send the jail name?

To show for example this message in Telegram:
`The IP: 150.136.60.xxx has been banned by 'apache-badbots'`

**Comment by deividgdt** [comment]
Hi Castillo92,

I've modified the script and the action file telegram.conf in order to pass the jail name to the telegram bot. I've already checked it, and it's working fine! 

![image](https://user-images.githubusercontent.com/42324150/103195404-8076a500-48e2-11eb-96e0-f88b74978883.png)

**Comment by castillo92** [comment]
> Hi Castillo92,
> 
> I've modified the script and the action file telegram.conf in order to pass the jail name to the telegram bot. I've already checked it, and it's working fine!
> 
> ![image](https://user-images.githubusercontent.com/42324150/103195404-8076a500-48e2-11eb-96e0-f88b74978883.png)

Wow! You made the moddificacion fastest than light! Thanks you very much!

I tried the new script and get one minor error:

https://github.com/deividgdt/fail2ban_telegram_notifications/blob/ec9bb77a17efbe6eb8a0df5c660378351dd78bcc/send_telegram_notif.sh#L38

That's where the new argument is missing. It should be:
` while getopts "a:n:b:u:" opt; do `

After fix it, it's working ! 😊

![telegram Notif F2B](https://user-images.githubusercontent.com/37965565/103210924-44a20680-4907-11eb-81c9-463321104e73.jpeg)




PD: I am going to try to do a Pull Request, but I never did before... If you do not receive it, please, edit the file please
EDIT 2: Thanks for your help @deividgdt. I was able to open a pull request. So I can help with something =)
